basePath: /
definitions:
  user.createUserRequest:
    properties:
      name:
        type: string
    type: object
  user.createUserResponse:
    properties:
      id:
        type: string
    type: object
  user.userDB:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
info:
  contact:
    name: voya.social
  description: A backend for voya.social written in Golang backend API using Fiber
    and MongoDB
  license:
    name: MIT
  title: Voya Backend
  version: "0.1"
paths:
  /users:
    get:
      consumes:
      - '*/*'
      description: fetch every user available.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/user.userDB'
            type: array
      summary: Get all users.
      tags:
      - users
    post:
      consumes:
      - '*/*'
      description: creates one user.
      parameters:
      - description: User to create
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/user.createUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.createUserResponse'
      summary: Create one user.
      tags:
      - users
swagger: "2.0"
