basePath: /
definitions:
  meditation.createMeditationRequest:
    properties:
      endTime:
        type: string
      meditationTime:
        type: string
      userId:
        type: string
    type: object
  meditation.createMeditationResponse:
    properties:
      id:
        type: string
    type: object
  meditation.meditationResponse:
    properties:
      meditationId:
        type: string
    type: object
  user.createUserRequest:
    properties:
      dateOfBirth:
        type: string
      email:
        type: string
      firstName:
        type: string
      id:
        type: string
      lastName:
        type: string
    type: object
  user.createUserResponse:
    properties:
      id:
        type: string
    type: object
  user.pluginType:
    enum:
    - meditation
    - workout
    type: string
    x-enum-varnames:
    - PluginTypeMeditation
    - PluginTypeWorkout
  user.updateUserRequest:
    properties:
      dateOfBirth:
        type: string
      email:
        type: string
      firstName:
        type: string
      id:
        type: string
      lastName:
        type: string
      plugins:
        items:
          $ref: '#/definitions/user.pluginType'
        type: array
    type: object
  user.userDB:
    properties:
      createdAt:
        type: string
      dateOfBirth:
        type: string
      email:
        type: string
      firstName:
        type: string
      id:
        type: string
      lastName:
        type: string
      plugins:
        items:
          $ref: '#/definitions/user.pluginType'
        type: array
    type: object
info:
  contact:
    name: Wholesome Living
  description: A backend for Wholesome Living written in Golang backend API using
    Fiber and MongoDB
  license:
    name: MIT
  title: Wholesome Living Backend
  version: "0.1"
paths:
  /meditation:
    post:
      consumes:
      - '*/*'
      description: Creates a new meditation.
      parameters:
      - description: Meditation to create
        in: body
        name: meditation
        required: true
        schema:
          $ref: '#/definitions/meditation.createMeditationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/meditation.createMeditationResponse'
      summary: Create meditation.
      tags:
      - meditation
  /meditation/{id}:
    get:
      description: fetch a single meditation session.
      parameters:
      - description: Meditation ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/meditation.meditationResponse'
      summary: Get a meditation session
      tags:
      - meditation
  /users:
    get:
      consumes:
      - '*/*'
      description: fetch every user available.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/user.userDB'
            type: array
      summary: Get all users.
      tags:
      - users
    post:
      consumes:
      - '*/*'
      description: creates one user.
      parameters:
      - description: User to create
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/user.createUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.createUserResponse'
      summary: Create one user.
      tags:
      - users
    put:
      consumes:
      - '*/*'
      description: update a user by id.
      parameters:
      - description: User to update
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/user.updateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.userDB'
      summary: Update a user.
      tags:
      - users
  /users/{id}:
    get:
      consumes:
      - '*/*'
      description: fetch a user by id.
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.userDB'
      summary: Get a user.
      tags:
      - users
swagger: "2.0"
